# -*- coding: utf-8 -*-
"""Superstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPwsMx1DgYuiFKF5jM6LA3pq48fbn9_8
"""

import kagglehub                      # Load data from kaggle
import pandas as pd                   # Dataframe manipulation library
import matplotlib.pyplot as plt       # Graphic/plot visualization library
import seaborn as sns                 # Graphic/plot visualization library
import statsmodels                    # Statistics Library
import patsy                          # For matrix design statistic
import os                             # Construct/system manipulations

"""# **Load Data**"""

path = kagglehub.dataset_download("vivek468/superstore-dataset-final")

print("Path to dataset files:", path)

# Construct the full path to the CSV file
csv_file_path = os.path.join(path, 'Sample - Superstore.csv')

# Load the CSV into a pandas DataFrame, specifying 'latin1' encoding
df = pd.read_csv(csv_file_path, encoding='latin1')

# Display the first 5 rows of the DataFrame
df.head()

# Calculate total duplicated rows in the entire dataset
print("1. Duplicated Data Validation")
duplicate_count = df.duplicated().sum()
print(f"Total duplicated rows: {duplicate_count}")
if duplicate_count > 0:
    print("Warning: Found duplicated data! Consider using df.drop_duplicates()")
else:
    print("Clean: No duplicated rows found.")

# Ensure Ship Date is not earlier than Order Date
# Assumes both columns have been converted to datetime format previously
print("\n2. Date Anomaly Validation")
date_anomaly = df[df['Ship Date'] < df['Order Date']]
anomaly_count = len(date_anomaly)
#-------------------------------------------------------------------------------
print(f"Total rows with Ship Date earlier than Order Date: {anomaly_count}")
if anomaly_count > 0:
    print("Warning: Found date anomalies! Displaying the anomalous rows:")
    # Display only important columns for verification
    print(date_anomaly[['Order ID', 'Order Date', 'Ship Date', 'Customer ID']].head())
else:
    print("Clean: All shipping dates are logically after or equal to order dates.")
#-------------------------------------------------------------------------------

# Check for negative values in columns that should logically always be positive
print("\n3. Illegal Values Validation")
cols_to_check = ['Sales', 'Quantity']
has_negative = False

for col in cols_to_check:
    negative_rows = df[df[col] < 0]
    negative_count = len(negative_rows)
    print(f"Total negative values in '{col}': {negative_count}")

    if negative_count > 0:
        has_negative = True
        print(f"Warning: Found negative values in {col}! Examples:")
        print(negative_rows[['Order ID', 'Customer ID', col]].head())

if not has_negative:
    print("Clean: No illegal negative values found in Sales or Quantity columns.")

"""# **Data Cleaning**"""

# Display rows have a missing values partially not all of it
df[df.isnull().any(axis=1)]

df.info()

# Replace data type from object/string to datetime
df[['Order Date', 'Ship Date']] = df[['Order Date', 'Ship Date']].apply(pd.to_datetime)
df.info()

"""# **Exploratory Data Analyst**"""

print("\nNumeric Column of Statistic\n")
print(df.describe().round(2))
print("\nCategorycal Column of Statistic")
print(df.describe(include=["object", "string"]))
print("\n")

"""## **Insight 1 | Discount Optimization**"""

# Identify rows with the most extreme losses
df_loss_major = df[df['Profit'] < 0].sort_values(by='Profit', ascending=True).head(10)

# View the correlation between Discount and Profit
correlation = df[['Discount', 'Profit', 'Sales']].corr()

# Group losses by Sub-Category and Discount
product_analysis = df[df['Profit'] < 0].groupby('Sub-Category')[['Profit', 'Discount','Quantity', 'Sales']].mean()

df['Total Cost'] = df['Sales'] - df['Profit']
df['Unit Cost'] = df['Total Cost'] / df['Quantity']
df['Org Unit Price'] = df['Sales'] / ((1 - df['Discount']) * df['Quantity'])

df.head()

# Calculate the maximum safe discount limit (Original Margin / Potential Sales)
df['BE_Discount'] = 1 - (df['Total Cost'] / (df['Org Unit Price'] * df['Quantity']))

# Filter data where profit is negative to see if the discount exceeds the safe limit
df_loss = df[df['Profit'] < 0]
print(df_loss[['Discount', 'BE_Discount', 'Profit']])

column_to_delete = 'Max_Safe_Discount'

# Grouping by discounts
diskon_perf = df.groupby('Discount').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Qty=('Quantity', 'sum'),
    Total_Profit=('Profit', 'sum'),
).reset_index()
print(diskon_perf)

plt.rcParams['figure.figsize'] = (8, 6)
sns.set_theme(style="whitegrid")

# Create a horizontal line at Profit = 0
sns.lineplot(data=diskon_perf, x='Discount', y='Total_Profit', marker='o', color='red', linewidth=2.5)

plt.axhline(0, color='black', linestyle='--', alpha=0.7)
plt.title('Effect of Discount on Total Profit', fontsize=12, fontweight='bold', pad=20)
plt.xlabel('Discount', fontsize=12)
plt.ylabel('Total Profit (USD)', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

# Aggregate by Product Name, sorted by the most Quantity
df_discount_20 = df[df['Discount'] == 0.20]

top_products_20 = df_discount_20.groupby('Product Name').agg(
    Total_Qty=('Quantity', 'sum'),
    Total_Sales=('Sales', 'sum')
    ).sort_values(by='Total_Qty', ascending=False)

print("\nTop 10 Most Profitable Products at 20% Discount\n")
print(top_products_20.head(10))

# Aggregate by Product Name, sorted by the most Quantity
df_discount_20 = df[df['Discount'] == 0.20]

top_products_20 = df_discount_20.groupby('Sub-Category').agg(
    Total_Qty=('Quantity', 'sum'),
    Total_Sales=('Sales', 'sum')
    ).sort_values(by='Total_Qty', ascending=False)

# Display the results
print("\nTop 10 Most Profitable Sub-Category at 20% Discount\n")
print(top_products_20.head(10))

# Identify states or regions contributing the largest total losses
state_profit_loss = df.groupby('State')['Profit'].sum().round(2).sort_values()
print("\nStates with the worst profit performance:")
print(state_profit_loss.head())

"""### **Business Narrative & Actionable Insights**

#### **Context:**
Discounts are originally designed to boost sales volume and acquire new customers. However, an unmonitored discount strategy can severely erode profit margins. This analysis aims to evaluate the correlation between discount rates and profitability, identifying where financial leakages occur.

#### **Key Findings:**
1. **The 20% Threshold Trap:** There is a strong negative correlation between high discounts and profitability. Aggressive discounting creates a major deficit. Specifically, a flat discount of **20% or more** triggers a significant downward spiral, shifting transactions from profitable to heavily negative.
2. **Break-Even (BE) Discount Breach:** Many transactions have exceeded their maximum safe discount limit (*BE_Discount*), meaning the company is selling products below their total cost of goods sold (COGS) and operational costs.
3. **High-Loss Drivers:** The financial loss is heavily concentrated in specific sub-categories—such as **Binders and Appliances**—and is heavily prevalent in certain geographic areas, notably **Texas and Ohio**.

#### **Strategic Recommendations:**
* **Implement a Discount Cap:** Immediately restrict flat discounts to a maximum of **15%** for high-risk sub-categories (Binders & Appliances) across all standard retail transactions.
* **Dynamic Bundling Strategy:** Instead of offering direct price cuts on single items, transition to a volume-based bundling strategy (e.g., *"Buy 3 Get 10% Off"*). This ensures the increased volume compensates for the margin drop.
* **Regional Pricing & Policy Audit:** Conduct a targeted review of sales operations in Texas and Ohio. Investigate whether local sales teams are over-relying on discounts to meet sales targets at the expense of regional profitability.

## **Insight 2: Shipment Durations**
"""

df['Shipping Duration'] = (df['Ship Date'] - df['Order Date']).dt.days
shipment = df.groupby('Ship Mode')['Shipping Duration'].mean().round(2).sort_values(ascending=True)
print(shipment)

plt.rcParams['figure.figsize'] = (8, 6)
sns.set_theme(style="whitegrid")

sns.barplot(x=shipment.index, hue=shipment.index , y=shipment.values, palette='viridis')
plt.title('Average Shipping Duration by Ship Mode', fontsize=12, fontweight='bold', pad=20)
plt.xlabel('Ship Mode', fontsize=12)
plt.ylabel('Average Shipping Duration (days)', fontsize=12)
plt.show()

"""### **Business Narrative & Actionable Insights**

#### **Context:**
Shipping efficiency is a cornerstone of customer satisfaction and operational logistics. This analysis evaluates the average fulfillment duration (the time elapsed between the `Order Date` and `Ship Date`) across different transportation modes to ensure the business meets its Service Level Agreements (SLAs).

#### **Key Findings:**
1. **SLA Alignment:** The operational data reflects a clear hierarchy in delivery speeds, where *Same Day* and *First Class* modes show the shortest durations, while *Standard Class* takes the longest.
2. **Bottleneck Assessment:** While the average duration aligns with general expectations, any significant variation or lag in the *Standard Class* or *Second Class* modes can lead to increased customer service inquiries and lower retention rates.

#### **Strategic Recommendations:**
* **Logistics Bottleneck Audit:** Identify the precise stage causing delays in the fulfillment pipeline (e.g., warehouse processing time vs. third-party carrier transit time).
* **Predictive Shipping Alerts:** Integrate a data-driven alert system that flags orders approaching their SLA threshold, allowing the operations team to expedite packing and dispatch.
* **Premium Upselling:** Utilize these baseline performance metrics in marketing campaigns to encourage customers to upgrade to *First Class* or *Same Day* shipping, thereby generating additional premium logistics revenue.

## **Insight 3: Customers Behavior**
"""

# Calculate the number of unique sub-categories per Order ID
order_summary = df.groupby('Order ID')['Sub-Category'].nunique().reset_index()
order_summary.columns = ['Order ID', 'Unique_SubCategory_Count']

# See how many orders contain more than 1 sub-category
multi_subcategory_orders = order_summary[order_summary['Unique_SubCategory_Count'] > 1]
cross_buying_percentage = (len(multi_subcategory_orders) / len(order_summary)) * 100

print(f"Cross-Buying Percentage {cross_buying_percentage:.2f}%")

# Find the anchor date (the last date in the entire dataset)
snapshot_date = df['Order Date'].max()

# Calculate RFM metrics
rfm = df.groupby('Customer ID').agg({

    # Recency: Days between snapshot_date and the customer's last purchase date
    'Order Date': lambda x: (snapshot_date - x.max()).days,
    # Frequency: Count of unique Order IDs for each customer
    'Order ID': 'nunique',
    # Monetary: Sum of Sales for each customer
    'Sales': 'sum'
}).sort_values(by='Sales',ascending=False)

# Rename columns for clarity
rfm.rename(columns={
    'Order Date': 'Recency',
    'Order ID': 'Frequency',
    'Sales': 'Monetary'
}, inplace=True)

print(rfm.head())

# Scoring Recency (Smallest value = Highest score)
rfm['R_Score'] = pd.qcut(rfm['Recency'], q=5, labels=[5, 4, 3, 2, 1])

# Scoring Frequency & Monetary (Highest value = Highest score)
# Note: For Frequency, many customers might have the exact same number of orders (e.g., just 1 order).
# Using .rank(method='first') prevents qcut from throwing a 'Bin edges must be unique' error.
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), q=5, labels=[1, 2, 3, 4, 5])
rfm['M_Score'] = pd.qcut(rfm['Monetary'], q=5, labels=[1, 2, 3, 4, 5])

# Optional: Create a combined string score (e.g., "554") for easy referencing
rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

import re     # Regex lib for segmentation

# Define the segmentation map based on Recency and Freq scores
segt_map = {
    r'[4-5][4-5]': 'Champions',
    r'[2-5][3-5]': 'Loyal Customers',
    r'[3-5][1-2]': 'Potential Loyalists',
    r'[4-5]1': 'New Customers',
    r'33': 'Need Attention',
    r'[2-3][1-2]': 'About to Sleep',
    r'2[1-2]': 'Customers Entering Risk',
    r'[1-2][3-4]': 'At Risk',
    r'15': 'Can\'t Lose Them',
    r'1[1-2]': 'Hibernating'
}

# Create an 'R-F' string combo to map against the dictionary
rfm['Segment'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str)

# Replace the R-F scores with the human-readable segment names
rfm['Segment'] = rfm['Segment'].replace(segt_map, regex=True)

# Preview the final DataFrame
print(rfm[['Recency', 'Frequency', 'Monetary', 'Segment']].head(10))

# Set figure size using rcParams to avoid plt.figure()
plt.rcParams['figure.figsize'] = (8, 6)
sns.set_theme(style="whitegrid")

# Get segment counts in descending order
segment_counts = rfm['Segment'].value_counts().reset_index()
segment_counts.columns = ['Segment', 'Count']

# Create barplot
ax = sns.barplot(x='Count', hue='Count' , legend=False, y='Segment', data=segment_counts, palette='viridis')
plt.title('Customer Distribution by RFM Segment', fontsize=16, fontweight='bold', pad=15)
plt.xlabel('Number of Customers', fontsize=12)
plt.ylabel('Segment', fontsize=12)
plt.tight_layout()

# Pivot table for R_Score vs F_Score (Average Monetary value)
heatmap_data = rfm.pivot_table(index='R_Score', columns='F_Score', values='Monetary', aggfunc='mean', observed=True)

# Sort index so R_Score 5 is at the top
heatmap_data = heatmap_data.sort_index(ascending=False)

plt.rcParams['figure.figsize'] = (8, 6)
sns.heatmap(heatmap_data, annot=True, fmt=".0f", cmap="YlGnBu", cbar_kws={'label': 'Average Monetary ($)'})
plt.title('RFM Heatmap: Average Monetary Value by R and F Scores', fontsize=14, fontweight='bold', pad=15)
plt.ylabel('Recency Score (Higher = More Recent)', fontsize=12)
plt.xlabel('Frequency Score (Higher = More Frequent)', fontsize=12)
plt.tight_layout()

"""### **Business Narrative & Actionable Insights**

#### **Context:**
Not all customers contribute equally to the business. To optimize marketing spend and maximize Customer Lifetime Value (CLV), we conducted an **RFM (Recency, Frequency, Monetary)** analysis to segment the customer base into distinct behavioral groups based on how recently they bought, how often they buy, and how much they spend.

#### **Key Findings:**
1. **Segment Distribution:** The segmentation reveals a diverse customer health profile. While we have a solid core of high-value customers (*Champions* and *Loyal Customers*), there is a visible portion of the database sitting in at-risk categories (*About to Sleep*, *At Risk*, or *Hibernating*).
2. **Revenue Disproportionality:** The heatmap highlights that a small percentage of top-tier segments (high R and F scores) contributes a massive share of the total *Monetary* value, emphasizing the risk if these customers churn.

#### **Strategic Recommendations:**
* **Champions & Loyal Customers (Nurture):** Launch an exclusive Loyalty Program or Early-Access Reward system. Do not waste marketing budget on discounting for this group; focus on relationship building and upselling premium products.
* **About to Sleep & Potential Loyalists (Re-engage):** Deploy personalized email automation workflows. Trigger a *"We Miss You"* campaign offering targeted incentives based on their previous purchase sub-categories to pull them back into the active cycle.
* **At Risk / Hibernating (Selective Win-Back):** Avoid expensive broad-spectrum campaigns. Filter this group by their past *Monetary* value; only target high-value historical spenders with aggressive win-back promotions, while letting low-value inactive accounts go to preserve marketing ROI.

## **Insight 4: Time-Series & Seasonality Growth**
"""

df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month

df.head(3)

# Calculate: Total Sales (sum), Average Sales (mean), and Number of Transactions (count)
monthly_tren = df.groupby(df['Order Date'].dt.to_period('M')).agg({
    'Sales': ['sum', 'mean'],
    'Order ID': 'nunique' # Count unique transactions per month
}).reset_index()

# 3. Clean up hierarchical column names (MultiIndex)
monthly_tren.columns = ['Month', 'Total_Sales', 'Avg_Sales', 'Total_Orders']

# 4. Convert 'Month' column back to string for easier visualization
monthly_tren['Month'] = monthly_tren['Month'].astype(str)

# Display the aggregated table
print(monthly_tren)

months_order = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

# Convert the 'Month' column to datetime objects and extract the month name
monthly_tren['Month_Name'] = pd.to_datetime(monthly_tren['Month']).dt.strftime('%b')

# Ensure monthly_tren has 'Month_Name' as a categorical type for correct ordering
monthly_tren['Month_Name'] = pd.Categorical(monthly_tren['Month_Name'], categories=months_order, ordered=True)

# Calculate average monthly sales and orders
avg_monthly_sales = monthly_tren.groupby('Month_Name', observed=True)['Total_Sales'].mean().reset_index()
avg_monthly_orders = monthly_tren.groupby('Month_Name', observed=True)['Total_Orders'].mean().reset_index()

# Line chart setup with two y-axes
plt.rcParams['figure.figsize'] = (8, 6)
sns.set_theme(style="whitegrid")

fig, ax1 = plt.subplots() # Create a figure and a set of subplots

# Plot Average Monthly Sales on ax1
color_sales = 'Teal'
ax1.set_xlabel('Month', fontsize=12)
ax1.set_ylabel('Average Total Sales (USD)', color=color_sales, fontsize=12)
sns.lineplot(x='Month_Name', y='Total_Sales', data=avg_monthly_sales, marker='o', color=color_sales, linewidth=2, markersize=7, ax=ax1, label='Average Sales')
ax1.tick_params(axis='y', labelcolor=color_sales)
ax1.grid(False) # Disable grid for ax1, let ax2 handle it

# Instantiate a second axes that shares the same x-axis
ax2 = ax1.twinx()

# Plot Average Monthly Orders on ax2
color_orders = 'Orange' # Choose a different color for orders
ax2.set_ylabel('Average Total Orders', color=color_orders, fontsize=12)
sns.lineplot(x='Month_Name', y='Total_Orders', data=avg_monthly_orders, marker='s', color=color_orders, linewidth=2, markersize=7, ax=ax2, label='Average Orders')
ax2.tick_params(axis='y', labelcolor=color_orders)
ax2.grid(True, alpha=0.3) # Enable grid for ax2

# Add title
plt.title('Average Monthly Sales and Orders Trend (Accumulated Across All Years)', fontsize=14, fontweight='bold', pad=15)

# Add legends for both lines
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc='upper left')
plt.tight_layout()
plt.show()

"""### **Business Narrative & Actionable Insights**

#### **Context:**
Retail businesses are highly susceptible to macroeconomic cycles and seasonal demand shifts. By analyzing historical sales and transaction volume trends month-over-month and accumulating them across multiple years, the business can accurately forecast peak seasons and optimize resource allocation.

#### **Key Findings:**
1. **Q4 Cyclical Surge:** The time-series visualization exhibits a clear, predictable seasonal pattern. Sales and transaction volumes experience a massive spike during the fourth quarter (**Q4 - especially September, November, and December**). This aligns with corporate budgeting cycles and year-end holiday shopping.
2. **Q1 Post-Holiday Slump:** Conversely, the first quarter (**Q1 - January and February**) routinely suffers from a severe revenue contraction as consumer spending cools down post-holidays.

#### **Strategic Recommendations:**
* **Supply Chain & Inventory Pre-Ordering:** Scale up inventory levels for top-selling product categories 2–3 months prior to the Q4 surge (starting in June/July) to prevent stockouts and capitalize entirely on peak demand.
* **Workforce & Logistics Scaling:** Adjust warehouse staffing and partner carrier capacities to handle the high transaction volume expected between September and December, minimizing fulfillment delays.
* **Q1 Defensive Campaigns:** To combat the low-revenue slump in January and February, launch aggressive clearance sales, new-year corporate contract renewals, or introduction of new product lines to stimulate artificial demand during the off-peak season.
"""

df.head(5)